node {

    stage('Checkout') {
        sh "echo start checkout"
        git url: GIT_REPO_URL, branch: 'deploy-frontend'
        sh "echo checkout done"
    }

    stage('Build') {
        sh "echo start building ,,"
        sh "cd frontend/sswm-front"

        dir ('frontend') {
            dir ('sswm-front') {
                sh "pwd"
                sh "npm install"
                sh 'npm run build'

            }
        }
        
        sh "echo build finished"
    }

    stage ('unit test') {

    }

    stage('Deploy') {
        // sh "echo deployment not yet determined"
    }
}

