node {
    stage('Checkout') {
        sh "echo start checkout"
        git url: 'https://a206:MdQZeq3wYF45cw6yCAQ1@lab.ssafy.com/s09-webmobile1-sub2/S09P12A206.git', branch: 'deploy-backend'
        sh "echo checkout done"
    }

    stage('Build') {
        sh "echo start building ,,"
        sh "cd backend/sswm"
        sh "java -version"
        dir ('backend') {
            dir ('sswm') {
                sh "chmod +x gradlew"
                sh "./gradlew compileJava"
            }
        }
        
        sh "echo build finished"
    }

    stage ('unit test') {

    }

    stage('Deploy') {
        // sh "echo deployment not yet determined"
    }
}
